### PR TITLE
Load XML from Data in LayoutLoading protocol

### PR DESCRIPTION
**Pull request by cadrega**
Add capabiilty to load XML from Data in LayoutLoading protocol

### CODE REVIEW

**Comment by nicklockwood** [comment]
@cadrega hi, sorry for the delay in reviewing this. It generally looks good, although I might tweak some of the method argument names for consistency. Also, there seems to be a problem with the Travis build.

**Comment by cadrega** [comment]
> 
> 
> @cadrega hi, sorry for the delay in reviewing this. It generally looks good, although I might tweak some of the method argument names for consistency. Also, there seems to be a problem with the Travis build.

Thanks @nicklockwood , of course you're welcome to fit this better to the Layout style.
I'm sorry about the Travis build errors! I don't nearly know how Travis works, but it seems that something has gone wrong with file encoding in my PR. The problem is on the first line of both changed files, at the (c) copyright character. What should I do now?

**Comment by cadrega** [comment]
This pull request is still valid for the 0.6.38 version.
The only bad thing that happened are the first lines of each file showing a seemingly inexistent change, perhaps due to file encoding.
I looked at the Travis error logs, and it seems that the "error" it returns is actually a warning that I even see in Xcode 9.3.1. It's not related to any code that I introduced.

**Comment by cadrega** [comment]
I created a new pull request which should be cleaner than this one: [new pull request](https://github.com/nicklockwood/layout/pull/181)

**Pull request closed without merging**
